# Creates a H2 database and wildfly instance
# Usage: docker-compose up
version: '2.0'
services:
  agedCare_wildfly:
    container_name: agedCare_wildfly_h2
    image: 'bizhubaustralia/skyve-wildfly'
    ports:
      - '8081:8080'
      - '9991:9990'
      - '8788:8787'
    environment:
      SKYVE_CONTENT: '/content/'
      SKYVE_DATASTORE_DIALECT: 'org.skyve.impl.persistence.hibernate.dialect.H2SpatialDialect'
      SKYVE_HOSTNAME: 'localhost'
      SKYVE_PORT: '8081'
      SKYVE_URL: 'http://localhost:8081'
      DATABASE_URL: 'agedCare_db'
      SKYVE_SECURITY_DOMAIN_NAME: 'agedCare'
      SKYVE_JNDI_NAME: 'agedCareDB'
      IDENTIFIER: 'DEV'
    volumes:
      - '../../deployments:/opt/jboss/wildfly/standalone/deployments/'
      - './content:/content'
